/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Row from '../packages/row/index.js';
import Picker from '../packages/picker/index.js';
import locale from 'jeffery-ui/src/locale';
import CollapseTransition from 'jeffery-ui/src/transitions/collapse-transition';

const components = [
  Button,
  Row,
  Picker,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$JYUI = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

module.exports = {
  version: '0.1.0',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Button,
  Row,
  Picker
};

module.exports.default = module.exports;
